x=input("Enter first number:")
y=input("Enter second number:")
sum=int(x)+int(y)
x=int(sum)-int(x)
print("first number after swapping:")
print(x)
y=int(sum)-int(y)
print("second number after swapping:")
print(y)